modLoader="javafml"
loaderVersion="[45,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="highlighter"
version="${file.jarVersion}"
displayName="Highlighter"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/521590"
logoFile="icon.png"
authors="Grend"
description="Highlights newly picked-up items in your inventory."

[[dependencies.highlighter]]
	modId="forge"
	mandatory=true
	versionRange="[45,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.highlighter]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.4]"
	ordering="NONE"
	side="BOTH"

[[dependencies.highlighter]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.1.8,)"
	ordering="NONE"
	side="BOTH"
