modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="highlighter"
version="${version}"
displayName="Highlighter"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/521590"
logoFile="icon.png"
authors="Grend, Mat0u5"
description="Highlights newly picked-up items in your inventory."

[[dependencies.highlighter]]
	modId="neoforge"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.highlighter]]
	modId="minecraft"
	type="required"
	versionRange="[26.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.highlighter]]
	modId="iceberg"
	type="required"
	versionRange="[1.4.2,)"
	ordering="AFTER"
	side="BOTH"

[[mixins]]
	config="highlighter.mixins.json"

[[mixins]]
	config="highlighter.neoforge.mixins.json"
